[package]
name = "makara"
version = "0.1.4"
edition = "2024"
description = "A Bevy UI simplifier that make it easy to build GUI app with bevy engine."
keywords = ["GUI", "Rust", "ECS"]
homepage = "https://github.com/MuongKimhong/makara"
repository = "https://github.com/MuongKimhong/makara"
license = "MIT"

[dependencies]
open = "5.3.3"
cosmic-text = "0.15.0"
smol_str = "0.2.2"
arboard = "3.6.1"
bevy = { version="0.17.3", features=[
    "debug",
    "default_font",
    "png",
    "jpeg",
    "webp",
    "https",
    "experimental_bevy_ui_widgets"
]}

[lib]
name = "makara"
path = "src/lib.rs"
