[package]
name = "makara"
version = "0.2.9"
edition = "2024"
description = "A Bevy UI simplifier that make it easy to build GUI app with bevy engine."
keywords = ["GUI", "Rust", "ECS"]
homepage = "https://github.com/MuongKimhong/makara"
repository = "https://github.com/MuongKimhong/makara"
license = "MIT"

[dependencies]
cosmic-text = "0.15.0"
webbrowser = "1.0.6"
smol_str = "0.2.2"
crossbeam-channel = "0.5.15"
bevy = { version="0.18.0", features=[
    "debug",
    "default_font",
    "png",
    "jpeg",
    "webp",
    "https",
    "experimental_bevy_ui_widgets"
]}
makara_macros = { git = "https://github.com/MuongKimhong/makara_macros", branch = "master", version = "0.1.0" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arboard = "3.6.1"
os = "0.1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.85"
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = [
  "Clipboard",
  "Navigator",
  "Window",
]}

[lib]
name = "makara"
path = "src/lib.rs"
